### PR TITLE
Update Get-IntuneOffboardingToolv2.ps1

### LINKED ISSUE #9: Permissions Question
I have global admin, intune admin, cloud device admin, and a few others but it still claims I am missing those permissions?

### PR DESCRIPTION
**Pull request by LDP-KStill**
Missing two quotation marks

### CODE REVIEW

**Comment by AndrewJNet** [comment]
Confirmed this fixes it for me. Resolves #9

**Comment by ugurkocde** [comment]
lgtm. Thanks @LDP-KStill

**Comment by blinkblinktwo** [comment]
By chance, does the auth button also need the quotes?
Like so?

`$AuthenticateButton.Add_Click({
        try {
            Connect-MgGraph -Scopes "Device.Read.All", "DeviceManagementManagedDevices.ReadWrite.All", "DeviceManagementServiceConfig.ReadWrite.All" -ErrorAction Stop
            $context = Get-MgContext`

**Comment by blinkblinktwo** [comment]
> lgtm. Thanks @LDP-KStill

By chance, does the auth button code also need the quotes on permissions?
Changed to like the below?

`$AuthenticateButton.Add_Click({ try { Connect-MgGraph -Scopes "Device.Read.All", "DeviceManagementManagedDevices.ReadWrite.All", "DeviceManagementServiceConfig.ReadWrite.All" -ErrorAction Stop $context = Get-MgContext`

**Pull request merged**
